language: node_js
env:
  - DISPLAY=':99.0'
before_install:
  - "sh -e /etc/init.d/xvfb start"
install:
  - "npm install"
  - "npm install -g bower"
  - "bower install"
script:
  - "./node_modules/.bin/grunt test"
  - "./node_modules/.bin/jasmine ./test/src/unit/test-micro-task-queue.js"
node_js:
  - "0.12"
  - "iojs"
